<!DOCTYPE HTML>
<html>
   <head>
      <meta charset='utf-8'>
      <title>Registration Success</title>
      <link rel='stylesheet' href='css/success.css'>
   </head>
   <body>
   		<div class="success">
      		<!-- <h1>Registration Success</h1> -->
      		<p>You’ve successfully registered. Click <a href='./login.php?action=login'>here</a> to go back to the home page and log in, or wait 5 seconds to be redirected.</p>
      	</div>
   </body>
</html>
